### ISSUE TITLE
Navigator Dashboard: Left Navigation Component

### ISSUE THREAD

**Issue by thinkharderdev** [code-for-charlottesville/housinghub#43]
Left navigation component 

See wireframe for UI design

3 Items:
   - Property Managers: View property managers
   - Property Search: Search for properties
   - Manage Properties: Add/edit properties

**Comment by dgoldstein1** [comment]
![Screen Shot 2020-04-26 at 4 20 04 PM](https://user-images.githubusercontent.com/15313378/80318690-ccb09900-87d9-11ea-80c2-56fdd2f0952f.png)

for reference
